### PR TITLE
Adding rendered site with search and export for all meetings

### PR DESCRIPTION
**Pull request by vsoch**
hey @jamespjh ! 

This is a really great resource, and I'd like to improve a user's ability to browse the content by way of rendering it into a site. This pull request will do that, specifically:

 - all yaml files are discovered in the _data folder and rendered to a list and a table
 - the table is searchable as well as exportable to csv, pdf, print, copy. excel, etc.
 - the entire site is searchable
 - listings have links to edit on GitHub, visit the website, search on AskCI, along with details for the next meeting.

The preview on my branch is at https://us-rse.org/eResearch-meeting-list/. You should be able to merge here and then edit some of the _config.yml links to be for your repo (and not usrse) and then turn on GitHub pages.

I hope you like it! I'd like to add tests for the data files after this work is merged - I noticed some with errors (dates in wrong format) that would warrant it.

### CODE REVIEW

**Comment by vsoch** [comment]
This will close #13

**Comment by vsoch** [comment]
And to be totally clear (in case I wasn't!) the usrse github pages is only turned on for your viewing. Once it's merged and turned on here we will turn it off! A lot of folks in usrse are excited about this resource so I added it to our org there :)

**Comment by jamespjh** [comment]
Thanks @vsoch this is an amazing contribution.

It's 118 files! It looks like many of those come from an upstream framework, and I think best practice would be to add that as a dependency and import during a build (using Travis, for example) rather than duplicate into this repository. Might you be willing to do that before I merge?

That's not at all to denigrate your wonderful contribution!

**Comment by vsoch** [comment]
It's docsy-jekyll, which I developed and maintain, a derivative of the GoLang based docsy. I customized it further for here, so I would not recommend that approach, but I can offer my infinite future support to address any issues that might arise.

**Comment by jamespjh** [comment]
OK, I'm persuaded. There's one conflict to IEEE-HPEC that needs resolving, and then I'll merge.

**Comment by vsoch** [comment]
Sounds good! Please assign me to any issues that come up with respect to the design or site otherwise, and I'll address promptly.

**Comment by vsoch** [comment]
And speaking of CI! When this goes through I can give a shot at writing a test to validate the data files.

**Comment by jamespjh** [comment]
OK cool, will you do the merge on your fork? (To keep the pull request structure pretty?)

**Comment by jamespjh** [comment]
Then I can use this thread in my next git class.

**Comment by vsoch** [comment]
What do you mean?

**Comment by jamespjh** [comment]
So, IEEE-HPEC is conflicting, you need to pull back into your fork the content that is in master on this fork, that'll merge that file into your fork, at which point this PR will be mergeable.

**Comment by jamespjh** [comment]
I can merge it, but I don't have push access to your fork, so then I'd have to fork your fork to do the merge, and it would get silly. ;-)

**Comment by vsoch** [comment]
You should be able to click "Resolve Conflict" to resolve the conflict, the gray box goes away, and then we can merge. I don't understand why you would need to fork my fork.

**Comment by vsoch** [comment]
Someone with write access would be able to click here

image

**Comment by jamespjh** [comment]
Resolve conflicts is greyed out, because it's too hard for the online merging thing. (Happens sometimes.)

So it says I have to use the command line.

So I can do that (I have done so). I could then push to my master, of course, but I don't have push rights to your fork, so I can't push my fix into the 'from' branch for this PR.

**Comment by jamespjh** [comment]
It's fine, never mind, I'll just push directly to master and close this PR.

**Comment by jamespjh** [comment]
There, done.

**Comment by vsoch** [comment]
Perfecto, git really does work! :)

**Comment by vsoch** [comment]
Let me know if you need any help with GitHub pages, when it's online I'll take usrse offline.

**Comment by jamespjh** [comment]
It's up, but just on my personal GHP at https://jamespjh.github.io/eResearch-meeting-list/ 

I'll open an issue to republish from this repo back to one of the RSE org sites.

**Comment by vsoch** [comment]
sounds good! I'll link to your site from the usrse fork for now.

**Comment by jamespjh** [comment]
Opened #37

**Pull request merged**
